services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      - DOCKER=1
    command:
      - dev
      - local-dev